-- Legacy schema for fresh databases. Existing, reviewed schemas must be explicitly baselined at 1.
create table users (
 id bigint generated by default as identity primary key,
 username varchar(255) not null unique,
 email varchar(255) not null unique,
 role varchar(255) not null check (role in ('USER','ADMIN'))
);
create table instruments (
 id bigint generated by default as identity primary key,
 symbol varchar(255) not null,
 name varchar(255) not null,
 type varchar(255) not null,
 price numeric(38,2) not null
);
create table virtual_accounts (
 id bigint generated by default as identity primary key,
 user_id bigint not null unique references users(id),
 balance numeric(38,2) not null
);
create table portfolio_assets (
 id bigint generated by default as identity primary key,
 user_id bigint not null references users(id),
 instrument_id bigint not null references instruments(id),
 quantity numeric(38,2) not null,
 average_price numeric(38,2) not null
);
create table transactions (
 id bigint generated by default as identity primary key,
 user_id bigint not null references users(id),
 instrument_id bigint not null references instruments(id),
 type varchar(255) check (type in ('BUY','SELL')),
 quantity numeric(38,2) not null,
 price numeric(38,2) not null,
 total_amount numeric(38,2) not null,
 transaction_time timestamp(6) not null
);
create table balance_requests (
 id bigint generated by default as identity primary key,
 user_id bigint,
 requested_amount numeric(38,2),
 status varchar(255) check (status in ('PENDING','APPROVED','REJECTED')),
 created_at timestamp(6)
);
